name: exavatar
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - aom=3.6.0
  - binutils=2.38
  - binutils_impl_linux-64=2.38
  - binutils_linux-64=2.38.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=12.1.0
  - cuda-compiler=12.4.1
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=11.6.55
  - cuda-cudart-static=12.4.127
  - cuda-cudart-static_linux-64=12.4.127
  - cuda-cuobjdump=12.4.127
  - cuda-cupti=12.1.105
  - cuda-cuxxfilt=12.4.127
  - cuda-documentation=12.1.55
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.4.127
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.5.1
  - cuda-libraries-static=12.4.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.4.127
  - cuda-nsight-compute=12.4.1
  - cuda-nvcc=12.4.131
  - cuda-nvdisasm=12.4.127
  - cuda-nvml-dev=12.4.127
  - cuda-nvprof=12.4.127
  - cuda-nvprune=12.4.127
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvrtc-static=12.4.127
  - cuda-nvtx=12.1.105
  - cuda-nvvp=12.4.127
  - cuda-opencl=12.4.127
  - cuda-opencl-dev=12.1.56
  - cuda-profiler-api=12.4.127
  - cuda-runtime=12.1.0
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.4.127
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.0
  - cuda-version=12.4
  - cuda-visual-tools=12.1.0
  - cudatoolkit-dev=11.7.0
  - cudnn=8.9.7.29
  - dataclasses=0.8
  - dav1d=1.2.1
  - dbus=1.13.18
  - deprecated=1.2.13
  - embree=4.3.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - fvcore=0.1.5.post20221221
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gds-tools=1.9.1.3
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - glm=0.9.9.8
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - iopath=0.1.10
  - jinja2=3.1.6
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - leptonica=1.82.0
  - lerc=3.0
  - libabseil=20240116.2
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=11.9.2.110
  - libcublas-static=12.4.5.8
  - libcufft=11.0.2.4
  - libcufft-dev=10.7.1.112
  - libcufft-static=11.2.1.3
  - libcufile=1.9.1.3
  - libcufile-dev=1.9.1.3
  - libcufile-static=1.9.1.3
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurand-static=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.6.1.9
  - libcusparse=12.0.2.55
  - libcusparse-dev=11.7.2.124
  - libcusparse-static=12.3.1.170
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libhwloc=2.9.3
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnpp=12.0.2.50
  - libnpp-dev=11.6.3.124
  - libnpp-static=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvfatbin-dev=12.4.127
  - libnvfatbin-static=12.4.127
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.55
  - libnvjitlink-static=12.4.127
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=11.6.2.124
  - libnvjpeg-static=12.3.1.117
  - libnvvm-samples=12.1.55
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=18.1.7
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nccl=2.22.3.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - nsight-compute=2024.1.1.4
  - nspr=4.35
  - nss=3.89.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.4.1
  - opentelemetry-api=1.30.0
  - pcre2=10.42
  - pixman=0.40.0
  - portalocker=3.0.0
  - pyembree=0.1.6
  - pysocks=1.7.1
  - python=3.10.16
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - sleef=3.6.1
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.11.0
  - termcolor=2.4.0
  - tesseract=5.2.0
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - wrapt=1.17.0
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yacs=0.1.8
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altered-midas==0.0.1
      - annotated-types==0.7.0
      - antialiased-cnns==0.3
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.3.0
      - beautifulsoup4==4.13.4
      - boto3==1.37.28
      - botocore==1.37.28
      - braceexpand==0.1.7
      - cffi==1.17.1
      - chrislib==0.0.1
      - chumpy==0.71
      - click==8.1.8
      - cloudpickle==3.1.1
      - coacd==1.0.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.2
      - cycler==0.12.1
      - cython==3.0.12
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - decord==0.6.0
      - diff-gaussian-rasterization==0.0.0
      - diffusers==0.27.0
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - etils==1.12.2
      - face-alignment==1.3.4
      - faiss-cpu==1.11.0
      - farama-notifications==0.0.4
      - filelock==3.14.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - gdown==5.2.0
      - genesis-world==0.2.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - grpcio==1.71.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==1.1.1
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - intrinsic==0.0.1
      - isaacsim-app==4.5.0.0
      - isaacsim-asset==4.5.0.0
      - isaacsim-benchmark==4.5.0.0
      - isaacsim-code-editor==4.5.0.0
      - isaacsim-core==4.5.0.0
      - isaacsim-cortex==4.5.0.0
      - isaacsim-example==4.5.0.0
      - isaacsim-extscache-kit==4.5.0.0
      - isaacsim-extscache-kit-sdk==4.5.0.0
      - isaacsim-extscache-physics==4.5.0.0
      - isaacsim-gui==4.5.0.0
      - isaacsim-kernel==4.5.0.0
      - isaacsim-replicator==4.5.0.0
      - isaacsim-rl==4.5.0.0
      - isaacsim-robot==4.5.0.0
      - isaacsim-robot-motion==4.5.0.0
      - isaacsim-robot-setup==4.5.0.0
      - isaacsim-ros1==4.5.0.0
      - isaacsim-ros2==4.5.0.0
      - isaacsim-sensor==4.5.0.0
      - isaacsim-storage==4.5.0.0
      - isaacsim-template==4.5.0.0
      - isaacsim-test==4.5.0.0
      - isaacsim-utils==4.5.0.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - libigl==2.5.1
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - lpips==0.1.4
      - lxml==5.3.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - moviepy==2.1.2
      - mujoco==3.3.0
      - multidict==6.3.2
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - omniverse-kit==106.5.0.162521
      - onnxruntime==1.21.1
      - open3d-python==0.3.0.0
      - opencv-python==4.10.0.84
      - opendatalab==0.0.10
      - openexr==3.3.3
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - osqp==0.6.7.post3
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.2.0
      - pathtools==0.1.2
      - pillow==10.4.0
      - pip==25.0.1
      - platformdirs==4.3.7
      - plotly==5.24.1
      - plyfile==1.1
      - pooch==1.8.2
      - proglog==0.1.11
      - promise==2.3
      - propcache==0.3.1
      - protobuf==3.20.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.8
      - pycollada==0.6
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygame==2.1.0
      - pygel3d==0.6.1
      - pyglet==2.1.3
      - pygltflib==1.16.0
      - pygments==2.19.1
      - pymeshlab==2023.12.post3
      - pynndescent==0.5.13
      - pyopengl==3.1.5
      - pyopengl-accelerate==3.1.5
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pyrender==0.1.45
      - pysdf==0.1.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytorch-lightning==2.5.1
      - pytz==2023.4
      - pyvirtualdisplay==3.0
      - pyvista==0.44.2
      - qdldl==0.1.7.post5
      - regex==2024.11.6
      - rich==13.4.2
      - rl-games==1.6.1
      - s3transfer==0.11.4
      - safetensors==0.5.3
      - sam-2==1.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scooby==0.10.0
      - seaborn==0.13.2
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - setuptools==60.2.0
      - shapely==2.1.0
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - smplx==0.1.28
      - soupsieve==2.7
      - sympy==1.13.1
      - taichi==1.7.3
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminaltables==3.1.10
      - tetgen==0.6.5
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - timm==1.0.15
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchgeometry==0.1.2
      - torchmetrics==1.7.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.32.1
      - trimesh==3.23.5
      - triton==3.2.0
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - ultralytics==8.3.101
      - ultralytics-thop==2.0.14
      - umap==0.1.1
      - umap-learn==0.5.7
      - urdfpy==0.0.22
      - urllib3==1.26.20
      - vtk==9.3.1
      - wandb==0.12.21
      - warp-lang==0.10.1
      - webdataset==0.2.111
      - werkzeug==3.1.3
      - xformers==0.0.29.post3
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - yarl==1.18.3
